<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="guide">
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add item'); ?>" href="<?php echo $this->url('', array('controller' => 'item', 'action' => 'update')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add item'); ?></a>
	</p>
	<h3><?php _e('List of item'); ?></h3>
	<table id="item-list" class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $item) { ?>
		<?php
		if($item['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($item['id']); ?></span></td>
			<td>
				<?php if($item['recommended'] == 1) { ?>
				<button id="button-<?php echo $item['id']; ?>" type="button" class="btn btn-link" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'recommend', 'id' => $item['id'], 'recommended' => '0')); ?>" ><i class="fa fa-heart"></i></button>
				<?php } else { ?>
				<button id="button-<?php echo $item['id']; ?>" type="button" class="btn btn-link" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'recommend', 'id' => $item['id'], 'recommended' => '1')); ?>" ><i class="fa fa-heart-empty"></i></button>	
				<?php } ?>
				<?php echo $this->escape($item['title']); ?>
			</td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $item['itemUrl']; ?>"><i class="fa fa-edit"></i> <?php _e('View'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Attach'); ?>" href="#"><i class="fa fa-edit"></i> <?php _e('Attach'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Review'); ?>" href="#"><i class="fa fa-edit"></i> <?php _e('Review'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Service'); ?>" href="#"><i class="fa fa-edit"></i> <?php _e('Service'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $item['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $item['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php //echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
		<span class="label label-danger"><?php _e('Trash'); ?></span>
	</p>
</div>
<script type="text/javascript" >
(function($){
    $("#item-list").on("click","button",function(){
       systemMessage.wait("<?php _e('Recommended in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.ajaxstatus==1){
          	 if(result.recommended==1){
	          	 var buttonClass = 'fa fa-heart';
          	 }
          	 if(result.recommended==0){
	          	 var buttonClass = 'fa fa-heart-empty';
          	 }
          	 $('#button-' + result.id + ' i').attr('class', buttonClass);
             systemMessage.succ(result.message);
          }else{
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>