<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->backbone();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="item-form" class="guide">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php include $this->templateComponent('forms'); ?>
</div>
<script type="text/javascript">
(function($){
    $("#item-form").on("click","#item-remove-image",function(){
        systemMessage.wait("<?php _e('Remove image item in process'); ?>");
        $.getJSON($(this).attr("data-link")).done(function(result){
            if(result.status==1){
                systemMessage.succ(result.message);
            }else{
                systemMessage.fail(result.message);
            }
        });
    });
})(jQuery)
</script>
<script>
(function($) {
    var page = {
        el: $('#item-form'),
        modal: $('<div class="modal fade">').appendTo(document.body),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('#item-find-location').on("click",this.locationAction);
            <?php foreach($locationLevel as $location) { ?>
            this.$('#form-location-<?php echo $this->escape($location["id"]); ?>').on("change",this.locationElement<?php echo $this->escape($location["id"]); ?>Action);
            <?php } ?>
        },
        <?php foreach($locationLevel as $location) { ?>
        locationElement<?php echo $this->escape($location["id"]); ?>Action: function(e) {
            var url = "<?php echo $this->url('', array('controller' => 'location', 'action' => 'formElementAjax')); ?>";
            var level = <?php echo $this->escape($location["child"]); ?>;
            var parent = $('#form-location-<?php echo $this->escape($location["id"]); ?>').val();
            $.getJSON(url + "level/" + level + "/parent/" + parent).done(function(result) {
                var htmlOptins = "<option value='0'><?php _e('Select element'); ?></option>";
                $.each(result, function( index, value ) {
                    htmlOptins = htmlOptins + "<option value='" + value.id + "'>" + value.title + "</option>";
                });
                $('#form-location-' + level).html(htmlOptins);
            });
        },
        <?php } ?>
    }
    page.init();
})(jQuery)
</script>