<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="guide">
	<h3><?php _e('Manage location category'); ?></h3>
	<div class="col-md-3">
		<div class="list-group">
			<a class="list-group-item" title="<?php _e('Location list'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Location list'); ?></a>
			<a class="list-group-item" title="<?php _e('Add category'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add category'); ?></a>
			<a class="list-group-item" title="<?php _e('Manage category'); ?>" href="<?php echo $this->url('', array('action' => 'manage')); ?>"><i class="fa fa-cog"></i> <?php _e('Manage category'); ?></a>
		</div>
	</div>
	<div class="col-md-9">
		<?php if (!empty($categoryList)) { ?>
		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th><?php _e('ID'); ?></th>
				<th><?php _e('Title'); ?></th>
				<th><?php _e('Action'); ?></th>
			</tr>
			<?php foreach($categoryList as $category) { ?>
			<tr>
				<td><?php echo $this->escape($category['id']); ?></td>
				<td><?php echo $this->escape($category['title']); ?></td>
				<td>
					<a class="btn btn-primary" title="<?php _e('Locations'); ?>" href="<?php echo $this->escape($category['url']); ?>"><i class="fa fa-eye"></i> <?php _e('Locations'); ?></a>
					<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->escape($category['edit']); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				</td>
			</tr>
			<?php } ?>
		</table>
		<?php } else { ?>
        <div class="alert alert-success"><?php _e('You can add new location category or select catelory for see list of all locations on that'); ?></div>
		<?php } ?>
	</div>
	<div class="clearfix"></div>
</div>