<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="guide">
	<h3><?php _e('List of all locations'); ?></h3>
	<div class="col-md-3">
		<?php if (!empty($locationLevel)) { ?>
		<div class="list-group">
		    <?php foreach ($locationLevel as $key => $value) { ?>
			<a href="<?php echo $this->url('', array('action' => 'index', 'level' => $key)); ?>" class="list-group-item <?php if ($key == $level) { ?>active<?php } ?>"><?php echo $value; ?></a>
		    <?php } ?>
		</div>
		<?php } ?>
	</div>
	<div class="col-md-9">
		<?php if (!empty($locationList)) { ?>
		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th><?php _e('ID'); ?></th>
				<th><?php _e('Title'); ?></th>
				<th><?php _e('Action'); ?></th>
			</tr>
			<?php foreach($locationList as $location) { ?>
			<tr>
				<td><?php echo $this->escape($location['id']); ?></td>
				<td><?php echo $this->escape($location['title']); ?></td>
				<td>
					<?php if (isset($location['add'])) { ?>
					<a class="btn btn-primary" title="<?php _e('Add child location'); ?>" href="<?php echo $this->escape($location['add']); ?>"><i class="fa fa-plus"></i> <?php _e('Add child location'); ?></a>
					<?php } ?>
					<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->escape($location['edit']); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				</td>
			</tr>
			<?php } ?>
		</table>
		<?php } ?>
		<?php if ($level == 1) { ?>
		<p><a class="btn btn-primary" title="<?php _e('Add top location'); ?>" href="<?php echo $this->url('', array('action' => 'add', 'level' => 1)); ?>"><i class="fa fa-plus"></i> <?php _e('Add top location'); ?></a></p>
		<?php } ?>
	</div>
	<div class="clearfix"></div>
</div>