<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="guide">
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add Service'); ?>" href="<?php echo $this->url('', array('controller' => 'service', 'action' => 'manage', 'item' => $item['id'])); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add Service'); ?></a>
	</p>
	<h3><?php echo sprintf(__('List of all service from %s'), $item['title']); ?></h3>
	<?php foreach($item['service'] as $service) { ?>
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title"><?php echo $this->escape($service['title']); ?></h3></div>
		<div class="panel-body"><?php echo sprintf(__('List of all servies from %s category'), $service['title']); ?></div>
		<table class="table">
			<tr>
				<th><?php _e('ID'); ?></th>
				<th><?php _e('Title'); ?></th>
				<th><?php _e('Price'); ?></th>
				<th><?php _e('Action'); ?></th>
			</tr>
			<?php foreach($service['parameter'] as $parameter) { ?>
			<?php
			if($parameter['status'] == 1) {
				$labelIdClass = 'label-success';	
			} else {
				$labelIdClass = 'label-warning';	
			}	
			?>
			<tr>
				<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($parameter['id']); ?></span></td>
				<td><?php echo $this->escape($parameter['title']); ?></td>
				<td><?php echo $this->escape($parameter['price_view']); ?></td>
				<td>
					<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('controller' => 'service', 'action' => 'manage', 'item' => $item['id'], 'id' => $parameter['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				</td>
			</tr>
			<?php } ?>
		</table>
	</div>
	<?php } ?>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
		<span class="label label-danger"><?php _e('Trash'); ?></span>
	</p>
</div>