<div class="guide-block">
	<?php if ($block['type'] == 'simple') { ?>
	<div class="guide-block-category clearfix">
		<ul class="nav nav-pills nav-stacked">
			<?php foreach($block['resources'] as $category) { ?>
			    <li><a title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['url']); ?>"><?php echo $this->escape($category['title']); ?></a></li>
			<?php } ?>
        </ul>
	</div>
	<?php } elseif($block['type'] == 'advanced') { ?>
	<?php $this->css($this->assetModule('css/tree.css', 'guide')); ?>
	<div class="guide-block-category-advanced">
    	<?php echo $block['treeHtml']; ?>
	</div>
	<script type="text/javascript">
	var MenuTree = {
    	collapse: function(element) {
        	element.slideToggle(600);
    	},
    	walk: function() {
        	$('a', '.guide-block-category-advanced').each(function() {
            	var $a = $(this);
            	var $li = $a.parent();
            	if ($a.next().is('ul')) {
                	var $ul = $a.next();
                	$a.click(function(e) {
                    	e.preventDefault();
                    	MenuTree.collapse($ul);
                    	$a.toggleClass('active');
                	});
            	}
        	});
    	}
	};
	MenuTree.walk();
	</script>
	<?php } ?>
</div>