<div class="guide-block">
    <div class="guide-block-item clearfix">
    <?php foreach($block['resources'] as $item) { ?>
        <div class="col-sm-6 col-md-3 itemBox">
            <div class="thumbnail">
                <?php if($item['image']) { ?>
                <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>">
                    <img src="<?php echo $item['mediumUrl']; ?>" alt="<?php echo $this->escape($item['title']); ?>" />
                </a>
                <?php } ?>
                <div class="caption">
                    <h4><a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><?php echo $this->escape($item['title']); ?></a></h4>
                    <p><?php echo $this->escape($item['address1']); ?></p>
                    <p><?php echo $this->escape($item['phone1']); ?></p>
                    <p><?php echo $this->escape($item['type']); ?></p>
                    <p><?php echo $this->escape($item['city']); ?> | <?php echo $this->escape($item['area']); ?></p>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
    <div class="guide-block-more clearfix">
        <a title="<?php echo _b('More items'); ?>" href="<?php echo $block['more-link']; ?>"><?php _b('More items'); ?></a>
    </div>
    <?php } ?>
</div>