<div class="guide-block">
    <div class="guide-block-item clearfix">
    <?php foreach($block['resources'] as $item) { ?>
        <div class="col-sm-6 col-md-3 itemBox">
            <div class="thumbnail">
                <?php if($item['image']) { ?>
                <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>">
                    <img src="<?php echo $item['mediumUrl']; ?>" alt="<?php echo $this->escape($item['title']); ?>" />
                </a>
                <?php } ?>
                <div class="caption">
                    <?php if($block['showtitle']) { ?>
                    <h4><a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><?php echo $this->escape($item['title']); ?></a></h4>
                    <?php } ?>
                    <?php if($block['showlocation']) { ?>
                    <p><strong><?php _e('Location'); ?></strong> : <?php echo $this->escape($item['city']); ?><?php if(!empty($item['area'])) { ?> | <?php echo $this->escape($item['area']); ?><?php } ?></p>
                    <?php } ?>
                    <?php if($block['showphone']) { ?>
                    <p><strong><?php echo _b('Phone'); ?></strong> : <?php echo $this->escape($item['phone1']); ?></p>
                    <?php } ?>
                    <?php if($block['showtype']) { ?>
                    <p><strong><?php echo _b('Type'); ?></strong> : <?php echo $this->escape($item['type']); ?></p>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
    <div class="guide-block-more clearfix">
        <a title="<?php echo _b('More items'); ?>" href="<?php echo $block['more-link']; ?>"><?php echo _b('More items'); ?></a>
    </div>
    <?php } ?>
</div>