<div class="guide-block">
    <div class="guide-block-item clearfix">
    <?php foreach($block['resources'] as $item) { ?>
        <div class="col-sm-6 col-md-4 itemBox">
            <div class="text-center">
                <?php if($item['image']) { ?>
                <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><img class="img-thumbnail" src="<?php echo $item['thumbUrl']; ?>" alt="<?php echo $this->escape($item['title']); ?>" /></a>
                <?php } ?>
                <!-- <h4>
                    <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><?php echo $this->escape($item['title']); ?></a>
                </h4> -->
            </div>
        </div>
    <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
    <div class="guide-block-more clearfix">
        <a title="<?php echo _b('More items'); ?>" href="<?php echo $block['more-link']; ?>"><?php _b('More items'); ?></a>
    </div>
    <?php } ?>
</div>