<div class="guide-search-block">
    <form class="<?php echo $block['form-class']; ?>" role="form" action="<?php echo $block['form-action']; ?>" method="post">
        <div class="form-group">
            <label class="sr-only" for="guideSearchTitle"><?php echo _b('Title'); ?></label>
            <input type="text" name="title" class="form-control" id="guideSearchTitle" placeholder="<?php echo _b('Title'); ?>">
        </div>
        <div class="form-group">
            <div class="form-control-static"> <?php echo _b('And / Or'); ?> </div>
        </div>
        <div class="form-group">
            <label class="sr-only" for="guideSearchLocation"><?php echo _b('Location'); ?></label>
            <input type="text" name="location" class="form-control" id="guideSearchLocation" placeholder="<?php echo _b('Location'); ?>">
        </div>
        <div class="form-group">
            <div class="form-control-static"> <?php echo _b('And / Or'); ?> </div>
        </div>
        <div class="form-group">
            <label class="sr-only" for="guideSearchService"><?php echo _b('Service'); ?></label>
            <input type="text" name="service" class="form-control" id="guideSearchService" placeholder="<?php echo _b('Service'); ?>">
        </div>
        <button type="submit" class="btn btn-default"><?php echo _b('Search'); ?></button>
    </form>
</div>