<?php if (isset($attach['image']) && !empty($attach['image'])) { ?> 
<div class="clearfix">
	<div class="attach-image">
		<?php foreach($attach['image'] as $image) { ?>
		<div class="col-sm-3 col-md-2">
			<div class="thumbnail">
				<a href="<?php echo $image['largeUrl']; ?>" title="<?php echo $this->escape($image['title']); ?>">
					<img src="<?php echo $image['mediumUrl']; ?>" alt="<?php echo $this->escape($image['title']); ?>" />
				</a>
			</div>
		</div>	
		<?php } ?>
	</div>	
</div>
<?php } ?>