<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="col-sm-6 col-md-4 itemBox">
    <div class="text-center">
        <?php if($item['image']) { ?>
        <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><img class="img-thumbnail" src="<?php echo $item['thumbUrl']; ?>" alt="<?php echo $this->escape($item['title']); ?>" /></a>
        <?php } ?>
        <h4>
            <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><?php echo $this->escape($item['title']); ?></a>
        </h4>
    </div>
</div>