<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="col-sm-12 col-md-4 itemBox">
    <div class="thumbnail">
        <?php if($item['image']) { ?>
        <a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>">
            <img src="<?php echo $item['mediumUrl']; ?>" alt="<?php echo $this->escape($item['title']); ?>" />
        </a>
        <?php } ?>
        <div class="caption">
            <h4><a title="<?php echo $this->escape($item['title']); ?>" href="<?php echo $this->escape($item['itemUrl']); ?>"><?php echo $this->escape($item['title']); ?></a></h4>
            <p><strong><?php _e('Location'); ?></strong> : <?php echo $this->escape($item['city']); ?><?php if(!empty($item['area'])) { ?> | <?php echo $this->escape($item['area']); ?><?php } ?></p>
            <p><strong><?php _e('Phone'); ?></strong> : <?php echo $this->escape($item['phone1']); ?></p>
            <p><strong><?php _e('Type'); ?></strong> : <?php echo $this->escape($item['type']); ?></p>
        </div>
    </div>
</div>