<?php if ($config['view_category'] && isset($category) && !empty($category)) { ?>
<div class="clearfix categoryItem">
	<div class="panel panel-default">
  		<div class="panel-heading">
  			<h2 class="panel-title"><?php echo $this->escape($category['title']); ?></h2>
  		</div>
		<div class="panel-body">
			<?php if(!empty($category['image'])) {  ?>
			<div class="pull-left gallery itemImageList">
				<img class="img-thumbnail" src="<?php echo $category['thumbUrl']; ?>" alt="<?php echo $this->escape($category['title']); ?>" />
			</div>
			<?php } ?>  
			<?php echo $category['description']; ?>
		</div>
	</div>
</div>
<?php } ?>
<?php if ($config['view_category'] && isset($categories) && !empty($categories)) { ?>
<div class="clearfix categoryList">
	<?php if($config['view_title']) { ?>
	<div class="page-header">
		<h4><?php _e('Category list'); ?></h4>
	</div>
    <?php } ?>
	<?php foreach($categories as $category) { ?>
	<div class="col-sm-3 col-md-2">
		<?php if($category['image']) { ?>
        <div class="categoryImage text-center"><a title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['categoryUrl']); ?>"><img class="img-thumbnail" src="<?php echo $category['thumbUrl']; ?>" alt="<?php echo $this->escape($category['title']); ?>" /></a></div>
        <div class="categoryTitle text-center"><a title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['categoryUrl']); ?>"><?php echo $this->escape($category['title']); ?></a></div>
		<?php } else { ?>
		<div class="categoryTitle"><a title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['categoryUrl']); ?>"><i class="fa fa-folder-open"></i> <?php echo $this->escape($category['title']); ?></a></div>
		<?php } ?>
	</div>
	<?php } ?>
</div>
<?php } ?>
<?php if (isset($categoryItem) && !empty($categoryItem)) { ?>
<div class="clearfix categoryItemList">
	<?php foreach($categoryItem as $category) { ?>
	<span class="categoryTitle">
		<a title="<?php echo $this->escape($category['title']); ?>" href="<?php echo $this->escape($category['categoryUrl']); ?>"><i class="fa fa-folder-open"></i> <?php echo $this->escape($category['title']); ?></a>
	</span>
	<?php } ?>
</div>
<?php } ?>