<?php
    $this->css($this->assetModule('css/front.css'));
	$this->jQuery();
	$this->js($this->assetModule('js/jquery.magnific-popup.min.js'));
	$this->footScript()->appendScript("$('.gallery').each(function() {
    	$(this).magnificPopup({
        	delegate: 'a',
        	type: 'image',
        	gallery: {
          	enabled:true
        	}
    	});
	});");
	$this->css($this->assetModule('css/magnific-popup.css'));
	// Load google map
    $this->footScript()->prependFile('https://maps.googleapis.com/maps/api/js?sensor=false');
    $this->footScript()->appendScript("
        var myLatlng = new google.maps.LatLng(" . $itemItem['map_longitude'] . ", " . $itemItem['map_latitude'] . ");
        var mapOptions = {
            zoom: 18,
            center: myLatlng
        }
        var map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);
        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            draggable:true,
            title: '" . $itemItem['title'] . "'
        });
    ");
?>
<div class="guide">
	<div class="itemItem">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo $this->escape($itemItem['title']); ?></h3>
		</div>
		<div class="panel-body">
			<div class="col-md-8">
				<div class="itemInfoBox well clearfix">
					<div><?php include $this->template('front/category'); ?></div>
					<div><?php include $this->template('front/tag'); ?></div>
				</div>
				<div class="col-md-6">
					<?php if(!empty($itemItem['address1'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Address 1'); ?></strong> : <?php echo $this->escape($itemItem['address1']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['address2'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Address 2'); ?></strong> : <?php echo $this->escape($itemItem['address2']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['city'])) { ?>
					<div class="itemInfoText"><strong><?php _e('City'); ?></strong> : <?php echo $this->escape($itemItem['city']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['zipcode'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Zip code'); ?></strong> : <?php echo $this->escape($itemItem['zipcode']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['phone1'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Phone 1'); ?></strong> : <?php echo $this->escape($itemItem['phone1']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['phone2'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Phone 2'); ?></strong> : <?php echo $this->escape($itemItem['phone2']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['mobile'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Mobile'); ?></strong> : <?php echo $this->escape($itemItem['mobile']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['website'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Website'); ?></strong> : <?php echo $this->escape($itemItem['website']); ?></div>
					<?php } ?>
					<?php if(!empty($itemItem['email'])) { ?>
					<div class="itemInfoText"><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($itemItem['email']); ?></div>
					<?php } ?>
				</div>
				<div class="col-md-6">
					<?php include $this->template('front/extra'); ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="itemImage gallery text-center">
					<div class="itemImageMain">
						<div class="col-sm-6 col-md-12">
							<div class="thumbnail">
								<a href="<?php echo $itemItem['largeUrl']; ?>" title="<?php echo $this->escape($itemItem['title']); ?>">
									<img src="<?php echo $itemItem['mediumUrl']; ?>" alt="<?php echo $this->escape($itemItem['title']); ?>" />
								</a>
							</div>
						</div>
					</div>
					<div class="itemImageAttach"><?php include $this->template('front/attach_image'); ?></div>
				</div>
			</div>
			<div class="col-md-12 clearfix">
        		<div class="productSocial pull-left clearfix">
            		<?php if($config['social_facebook']) { ?>
            		<span class="productFacebook"><?php echo $this->facebook(); ?></span>
            		<?php } ?>
            		<?php if($config['social_twitter']) { ?>
            		<span class="productTwitter"><?php echo $this->twitter(); ?></span>
            		<?php } ?>
            		<?php if($config['social_gplus']) { ?>
            		<span class="productPlusone"><?php echo $this->plusone(); ?></span>
            		<?php } ?>
        		</div>
        		<div class="clearfix"></div>
    		</div>
			<!-- Nav tabs -->
			<div class="col-md-12">
				<ul class="nav nav-tabs nav-pills nav-justified">
					<li class="active"><a href="#tab-1" data-toggle="tab"><?php _e('Map'); ?></a></li>
					<li><a href="#tab-2" data-toggle="tab"><?php _e('Description'); ?></a></li>
					<li><a href="#tab-3" data-toggle="tab"><?php _e('Services'); ?></a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active itemTabBody" id="tab-1">
						<div id="map_canvas"></div>
					</div>
					<div class="tab-pane itemTabBody" id="tab-2">
						<div class="itemSummary"><?php echo $itemItem['summary']; ?></div>
						<div class="itemDescription"><?php echo $itemItem['description']; ?></div>
						<div class="itemMedia">
							<?php include $this->template('front/attach_audio'); ?>
					    	<?php include $this->template('front/extra_audio'); ?>
					    	<?php include $this->template('front/attach_video'); ?>
					    	<?php include $this->template('front/extra_video'); ?>
						</div>
					</div>
					<div class="tab-pane itemTabBody" id="tab-3">
						<?php include $this->template('front/service'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php //include $this->template('front/attach'); ?>
	<?php //include $this->template('front/review'); ?>
	<?php //include $this->template('front/list'); ?>
	</div>
</div>