<?php
    $this->css($this->assetModule('css/front.css'));
?>
<div class="guide">
	<div class="guide-dashboard guide-manage clearfix">
        <div class="col-md-3">
			<div class="thumbnail" style="padding: 10px;">
        		<div class="media">
            		<div class="pull-left">
            			<?php echo $customer['avatar']; ?>
            		</div>
            		<div class="media-body">
                		<h5 class="media-heading">
                			<?php echo $this->escape($customer['first_name']); ?> 
                			<?php echo $this->escape($customer['last_name']); ?>
                		</h5>
                		<span class="text-muted">
                			<?php echo $this->escape($customer['company']); ?>
                		</span>
            		</div>
        		</div>
			</div>
			<div class="list-group">
				<a title="<?php _e('List of items'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'dashboard')); ?>" class="list-group-item active"><?php _e('List of items'); ?></a>
				<a title="<?php _e('New item'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'update')); ?>" class="list-group-item"><?php _e('New item'); ?></a>
				<a title="<?php _e('Payment history'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'log')); ?>" class="list-group-item"><?php _e('Payment history'); ?></a>
				<a title="<?php _e('Edit information'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'edit')); ?>" class="list-group-item"><?php _e('Edit information'); ?></a>
			</div>
		</div>
		<div class="col-md-9">
			<h3><?php _e('List of item'); ?></h3>
			<table id="item-list" class="table table-striped table-bordered table-condensed">
				<tr>
					<th><?php _e('ID'); ?></th>
					<th><?php _e('Title'); ?></th>
					<th><?php _e('Start'); ?></th>
					<th><?php _e('End'); ?></th>
					<th><?php _e('Action'); ?></th>
				</tr>
				<?php foreach($list as $item) { ?>
				<?php
				if($item['status'] == 1) {
					$labelIdClass = 'label-success';	
				} else {
					$labelIdClass = 'label-warning';	
				}	
				?>
				<tr>
					<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($item['id']); ?></span></td>
					<td><?php echo $this->escape($item['title']); ?></td>
					<td><?php echo $this->escape($item['time_start_view']); ?></td>
					<td><?php echo $this->escape($item['time_end_view']); ?></td>
					<td>
						<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="#"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
					</td>
				</tr>
				<?php } ?>
			</table>
			<p>
				<span class="label label-success"><?php _e('Published'); ?></span>
				<span class="label label-warning"><?php _e('Pending review'); ?></span>
			</p>
		</div>
	</div>
</div>