<?php
    $this->css(array(
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->backbone();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="item-form" class="guide">
	<div class="guide-manage clearfix">
        <div class="col-md-3">
			<div class="thumbnail" style="padding: 10px;">
        		<div class="media">
            		<div class="pull-left">
            			<?php echo $customer['avatar']; ?>
            		</div>
            		<div class="media-body">
                		<h5 class="media-heading">
                			<?php echo $this->escape($customer['first_name']); ?> 
                			<?php echo $this->escape($customer['last_name']); ?>
                		</h5>
                		<span class="text-muted">
                			<?php echo $this->escape($customer['company']); ?>
                		</span>
            		</div>
        		</div>
			</div>
			<div class="list-group">
				<a title="<?php _e('List of items'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'dashboard')); ?>" class="list-group-item"><?php _e('List of items'); ?></a>
				<a title="<?php _e('New item'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'update')); ?>" class="list-group-item active"><?php _e('New item'); ?></a>
				<a title="<?php _e('Payment history'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'log')); ?>" class="list-group-item"><?php _e('Payment history'); ?></a>
				<a title="<?php _e('Edit information'); ?>" href="<?php echo $this->url('', array('controller' => 'manage', 'action' => 'edit')); ?>" class="list-group-item"><?php _e('Edit information'); ?></a>
			</div>
		</div>
		<div class="col-md-9">
			<div class="progress progress-striped active">
				<div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
					<span class="sr-only">20% Complete</span>
				</div>
			</div>
            <?php include $this->templateComponent('forms'); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
(function($){
    $("#item-form").on("click","#item-remove-image",function(){
        systemMessage.wait("<?php _e('Remove image item in process'); ?>");
        $.getJSON($(this).attr("data-link")).done(function(result){
            if(result.status==1){
                systemMessage.succ(result.message);
            }else{
                systemMessage.fail(result.message);
            }
        });
    });
})(jQuery)
</script>
<script>
(function($) {
    var page = {
        el: $('#item-form'),
        modal: $('<div class="modal fade">').appendTo(document.body),
        $: function(selector) {
            return this.el.find(selector);
        },
        init: function() {
            _.bindAll(this);
            this.$('#item-find-location').on("click",this.locationAction);
            <?php foreach($locationLevel as $location) { ?>
            this.$('#form-location-<?php echo $this->escape($location["id"]); ?>').on("change",this.locationElement<?php echo $this->escape($location["id"]); ?>Action);
            <?php } ?>
        },
        <?php foreach($locationLevel as $location) { ?>
        locationElement<?php echo $this->escape($location["id"]); ?>Action: function(e) {
            var url = "<?php echo $this->url('', array('controller' => 'manage', 'action' => 'formElementAjax')); ?>";
            var level = <?php echo $this->escape($location["child"]); ?>;
            var parent = $('#form-location-<?php echo $this->escape($location["id"]); ?>').val();
            $.getJSON(url + "/level/" + level + "/parent/" + parent).done(function(result) {
                var htmlOptins = "<option value='0'><?php _e('Select element'); ?></option>";
                $.each(result, function( index, value ) {
                    htmlOptins = htmlOptins + "<option value='" + value.id + "'>" + value.title + "</option>";
                });
                $('#form-location-' + level).html(htmlOptins);
            });
        },
        <?php } ?>
    }
    page.init();
})(jQuery)
</script>